---

#-------------------------------------------------------------------------------
# VARIABLES
#-------------------------------------------------------------------------------

- name: 'include variables'
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "vars/{{ ansible_distribution_version }}.yml"
      - 'vars/main.yml'
      skip: 'true'
  tags:
    - remove
    - wget

#-------------------------------------------------------------------------------
# PACKAGING
#-------------------------------------------------------------------------------

- name: 'package remove wget'
  package:
    state: 'absent'
    name: "{{ package_name_wget }}"
  register: result_wget_r
  until: result_wget_r is succeded
  retries: 3
  tags:
    - remove
    - wget
